name: Build the library

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v27

      - uses: cachix/cachix-action@v14
        with:
          name: doctordalek1963
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build the library
        run: nix develop --command bash -c "lake exe cache get && lake build Library"
